CREATE TABLE IF NOT EXISTS users (
	id SERIAL PRIMARY KEY,
	login TEXT NOT NULL,
	password TEXT NOT NULL,
	mail TEXT NOT NULL
);



CREATE TABLE IF NOT EXISTS movies (
	id SERIAL NOT NULL PRIMARY KEY,
	title TEXT NOT NULL,
	url TEXT NOT NULL,
	description TEXT NOT NULL,
	poster TEXT NOT NULL

);

CREATE TABLE IF NOT EXISTS orders (
	id SERIAL NOT NULL PRIMARY KEY,
	date DATE NOT NULL,
	user_id INTEGER NOT NULL REFERENCES users(id)
);

